{% set name = "bw2io" %}
{% set version = "0.9.dev23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e95fc1954ec40cb73e7b06ee57394bf779a79d57ff2e02e3777f4656108ab64d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - bw2calc >=2.0.dev14
    - bw2data >=4.0.dev27
    - bw2parameters >=1.1.0
    - bw_migrations>=0.2
    - bw_processing>=0.8.5
    - lxml
    - mrio_common_metadata
    - numpy
    - openpyxl
    - platformdirs
    - requests
    - scipy
    - stats_arrays>=0.6.5
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - bw2io

about:
  home: https://github.com/brightway-lca/brightway2-io
  summary: 'Tools for importing and export life cycle inventory databases'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/brightway-lca/brightway2-io

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
