{% set name = "bw2io" %}
{% set version = "0.9.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 567e96d7539016b119888e17750cb42f066f4e6ce76706d3c641900b5a7fe6a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bw_migrations >=0.2
    - bw_processing >=1.0
    - bw2calc >=2.0
    - bw2data >=4.3
    - bw2parameters >=1.1.0
    - lxml
    - mrio_common_metadata
    - numpy <2
    - openpyxl
    - platformdirs
    - pydantic
    - pyecospold
    - python >={{ python_min }}
    - randonneur >=0.6
    - randonneur_data >=0.5.4
    - requests
    - scipy
    - sparqlwrapper
    - stats_arrays >=0.6.5
    - tqdm
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - bw2io
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/brightway-lca/brightway2-io
  summary: 'Tools for importing and export life cycle inventory databases'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/brightway-lca/brightway2-io

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
