{% set name = "bw2io" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7d3c75f7018a0edfb52a8925fa990f85c25cb80a84b08fde58760baf356ce52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bw_migrations >=0.2
    - bw_processing >=0.8.5
    - bw_simapro_csv >=0.2.3
    - bw2calc >=2.0
    - bw2data >=4.0
    - bw2parameters >=1.1.0
    - lxml
    - mrio_common_metadata
    - multifunctional >=0.5
    - numpy
    - openpyxl
    - platformdirs
    - pydantic
    - pyecospold
    - python >={{ python_min }}
    - randonneur >=0.4
    - randonneur_data
    - requests
    - scipy
    - sparqlwrapper
    - stats_arrays >=0.6.5
    - tqdm
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - bw2io
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/brightway-lca/brightway2-io
  summary: 'Tools for importing and export life cycle inventory databases'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/brightway-lca/brightway2-io

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
