{% set name = "bw2io" %}
{% set version = "0.9.dev22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fde9020f8143c0dfcaa6c9ddd56ad37658df249e245bebc6958e5e7dd91e4567

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - bw2calc >=1.7.4
    - bw2data >=3.5.1
    - bw2parameters >=0.7.1
    - bw_migrations
    - bw_processing
    - lxml
    - mrio_common_metadata
    - numpy
    - openpyxl
    - platformdirs
    - requests
    - python >=3.6
    - scipy
    - stats_arrays
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - bw2io

about:
  home: https://github.com/brightway-lca/brightway2-io
  summary: 'Tools for importing and export life cycle inventory databases'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/brightway-lca/brightway2-io

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
